[package]
name = "algotest-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
algotest-domain = { path = "../domain" }
chrono.workspace = true
csv.workspace = true
postgres = { version = "0.19.14", features = ["with-chrono-0_4"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
