[package]
name = "algotest-rust-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
algotest-domain = { path = "../domain" }
algotest-engine = { path = "../engine" }
algotest-optimizer = { path = "../optimizer" }
algotest-storage = { path = "../storage" }
axum.workspace = true
chrono.workspace = true
rust_xlsxwriter.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tower-http.workspace = true
zip.workspace = true
